import type {Metadata} from "next";
import localFont from "next/font/local";
import {Poppins} from "next/font/google";
import "./globals.css";
import "boxicons/css/boxicons.min.css";
// import { Toaster } from "@/components/ui/toaster";
import {Toaster} from "@/components/ui/sonner"
import {ThemeProvider} from "@/components/layout/theme-provider/theme-provider";
import Loading from "@/app/admin/loading";
import React, {Suspense} from "react";

// Import Poppins from Google Fonts
const poppins = Poppins({
    subsets: ["latin"],
    weight: ["400", "700"], // Add more weights if needed
    variable: "--font-poppins",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" className="layout"
            // dir="rtl"
        >
        <body
            className={`${poppins.variable} antialiased font-normal`}
        ><Suspense fallback={<Loading/>}>
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                {children}
            </ThemeProvider>
        </Suspense>
        <Toaster/>
        </body>

        </html>
    );
}
